general {
    lock_cmd = pidof hyprlock || hyprlock       # Запускать hyprlock, если он еще не запущен
    before_sleep_cmd = loginctl lock-session    # ОБЯЗАТЕЛЬНО блокировать перед сном (и при закрытии крышки)
    after_sleep_cmd = hyprctl dispatch dpms on  # Включать экран при пробуждении
}

# 1. Блокировка экрана через 5 минут (300 секунд) бездействия
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Выключение дисплея через 5.5 минут (330 секунд) (экономия батареи)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
